### ISSUE TITLE
[YBUG.IO] I am having multiple failed...

### ISSUE THREAD

**Issue by creed-victor** [DistributedCollective/Sovryn-frontend#894] opened 2021-04-24 12:48 UTC
I am having multiple failed transactions trying to supply SOV liquidity using the Liquality wallet. Using average speed, just tried fastest and still getting failed transaction- contract reverted

*Source url:* https://live.sovryn.app/wallet
*Reported by:* js4spencer@yahoo.com
*Reported at:* 24 Apr at 12:48 UTC

*Location:* CH, Zurich, Zurich
*Browser:* Chrome 89.0.4389.128

*OS:* Windows 10.0
*Screen:* 1280x720
*Viewport:* 1280x578

*Screenshot:*
![Screenshot](https://ybug.io/data/reports/3f1jrxvzrhkn1b975t8b/hmydfpfzx5923058ndy8/screenshot.jpg?_token=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpYXQiOjE2MTkyNjg0ODksImRhdGEiOnsicmVwb3J0IjoiaG15ZGZwZnp4NTkyMzA1OG5keTgiLCJ1c2VyIjoiR2l0SHViIn19.8jT9vd37N-y_rtVxp9tT3T4WIfxKUxJMEwbuqWOOkdM)

For more details please visit report page on Ybug:
[https://ybug.io/dashboard/reports/detail/hmydfpfzx5923058ndy8](https://ybug.io/dashboard/reports/detail/hmydfpfzx5923058ndy8)

**Comment by soulBit** [comment] 2021-05-01 16:39
Closing as duplicate of #896

**Closed by soulBit** 2021-05-01 16:39 UTC
