### ISSUE TITLE
[YBUG.IO] Conecto wallet y se queda...

### ISSUE THREAD

**Issue by creed-victor** [DistributedCollective/Sovryn-frontend#780] opened 2021-04-17 16:20 UTC
Conecto wallet y se queda pantalla en negro. No funciona

*Source url:* https://live.sovryn.app/
*Reported by:* joanrah@yahoo.com
*Reported at:* 17 Apr at 16:20 UTC

*Location:* CL, Santiago Metropolitan, Providencia
*Browser:* Chrome 86.0.4240.75

*OS:* macOS 10.14.0
*Screen:* 1440x900
*Viewport:* 1414x703

*Screenshot:*
![Screenshot](https://ybug.io/data/reports/3f1jrxvzrhkn1b975t8b/jvtkjm40m097h8pnn75r/screenshot.jpg?_token=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpYXQiOjE2MTg2NzY0MjgsImRhdGEiOnsicmVwb3J0IjoianZ0a2ptNDBtMDk3aDhwbm43NXIiLCJ1c2VyIjoiR2l0SHViIn19.VUPJM4Mf2Md3j7Som67gR5Q75YXYc_9XXlqIX8nwaOI)

For more details please visit report page on Ybug:
[https://ybug.io/dashboard/reports/detail/jvtkjm40m097h8pnn75r](https://ybug.io/dashboard/reports/detail/jvtkjm40m097h8pnn75r)

**Comment by soulBit** [comment] 2021-04-17 22:35
Possible duplicate of #773

**Closed** 2021-05-14 15:55 UTC
Labels: bug, investigate
