### ISSUE TITLE
[YBUG.IO] One of my Supply transactions...

### ISSUE THREAD

**Issue by creed-victor** [DistributedCollective/Sovryn-frontend#795] opened 2021-04-18 03:05 UTC
One of my Supply transactions didn't appear here so I withdrew and now I'm incorrectly showing a negative balance. Please help. 0x8d...7010

*Source url:* https://live.sovryn.app/liquidity
*Reported by:* 
*Reported at:* 18 Apr at 03:05 UTC

*Location:* US, Texas, Dallas
*Browser:* Chrome 89.0.4389.128

*OS:* macOS 11.2.3
*Screen:* 1920x1080
*Viewport:* 1440x821

*Screenshot:*
![Screenshot](https://ybug.io/data/reports/3f1jrxvzrhkn1b975t8b/fqddvw254q05r352j25x/screenshot.jpg?_token=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpYXQiOjE2MTg3MTUxMzksImRhdGEiOnsicmVwb3J0IjoiZnFkZHZ3MjU0cTA1cjM1MmoyNXgiLCJ1c2VyIjoiR2l0SHViIn19.Y6f4tkm3yz2cdA9IhPt2Cr8-VqRlUfurWu3uTJoTy6s)

For more details please visit report page on Ybug:
[https://ybug.io/dashboard/reports/detail/fqddvw254q05r352j25x](https://ybug.io/dashboard/reports/detail/fqddvw254q05r352j25x)

**Comment by soulBit** [comment] 2021-04-18 17:43
Closing as duplicate of #794

**Closed by soulBit** 2021-04-18 17:43 UTC
