### ISSUE TITLE
MAX BUTTON TO LEND DOC FUNDS IS CAUSING A ROUNDING UP ERROR

### ISSUE THREAD

**Issue by jjmr007** [DistributedCollective/Sovryn-frontend#1222] opened 2021-05-30 18:52 UTC
**Describe the bug**
A user [tryied to lend](https://blockscout.com/rsk/mainnet/tx/0xcf933b0606a15ee6d80595b7ede0ff5ad3f28f7941b7ce68c24a0df74744dfc4/internal-transactions) around 500 DoC to the LoanToken protocol. Htting the MAX button of the UI the transaction prepared by the web interface roud up the amount of funds to be lent to 500.235088485414500000 DOC, but the user's balanceOf in DoC is only: 500.235088485414498161 causing a reverting error.

**To Reproduce**

1. Go to 'https://live.sovryn.app/lend'
2. Click on 'LEND -> DEPOSIT -> MAX'
3. Hit "Deposit DOC"
4. Approve/Confirm the transaction on your wallet. In some cases the transaction reverts with an error:
`Error Message: SafeMath: subtraction overflow`

**Expected behavior**
All transactions should succeed.

**Screenshots**
![1_1](https://user-images.githubusercontent.com/17028457/120116528-9371f780-c156-11eb-9309-3c9e0b4914d1.png)
![2_1](https://user-images.githubusercontent.com/17028457/120116536-98cf4200-c156-11eb-99dd-cd74f5cc9612.png)

**Desktop (please complete the following information):**

OS: Linux Ubuntu 18.04.5 LTS
Browser: Chrome 90.0.4430.212 (Official Build) (64-bit)
Wallet: Nifty 5.2.5

**Comment by soulBit** [comment] 2021-06-04 15:20
Duplicate of #1110

**Closed by soulBit** 2021-06-04 15:20 UTC
Labels: bug
